### ISSUE TITLE
Option Output Folder

### ISSUE THREAD

**Issue by BrunoFischerGermany** [i1v/googleplay#1]
Helllo!

I use the last version from 87z.

There was an Option -o for an Output Folder.

is this removed?

**Comment by i1v** [comment]
the current options are here:

https://github.com/i1v/googleplay/blob/64b485f8f0de65c13ceac59d7d5c205715150060/cmd/googleplay/main.go#L23-L39

I removed the `-o` option, because I do not need it, and it was becoming a maintenance burden. if you wish for the feature, you can add it yourself, or I can add it for a fee. Let me know if you are interested to do that.

**Comment by BrunoFischerGermany** [comment]
My Skills for go are not so good. so i have to move the apk to the right folder with the "mv".

thanks
