### ISSUE TITLE
File_Metadata.Download_URL return not url but id

### ISSUE THREAD

**Issue by moeshin** [i1v/googleplay#7]
https://github.com/i1v/googleplay/blob/1ed3938a5a44498db4c9898cdabaab04f6f989f6/delivery.go#L75-L78

Details() -> File() -> Download_URL()

**Comment by i1v** [comment]
please provide example app

**Comment by moeshin** [comment]
`com.google.android.youtube`

```golang
for i, metadata := range details.File() {
	fmt.Println(i, metadata)
	fmt.Println(metadata.Download_URL())
}
```

```text
0 {map[1:0 2:1536153024 3:22698280 5:19346632]}
 field 4 is nil, not Raw
1 {map[1:0 2:1536153024 3:1190778 4:{[99 111 110 102 105 103 46 109 100 112 105] config.mdpi map[]} 5:811966]}
config.mdpi <nil>
2 {map[1:0 2:1536153024 3:446873 4:{[99 111 110 102 105 103 46 122 104] config.zh map[]} 5:147764]}
config.zh <nil>
3 {map[1:0 2:1536153024 3:22812411 4:{[99 111 110 102 105 103 46 97 114 109 54 52 95 118 56 97] config.arm64_v8a map[]} 5:22649924]}
config.arm64_v8a <nil>
```

**Comment by i1v** [comment]
so `/fdfe/delivery` returns a `ResponseWrapper`:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/Response.java#L34

we request field 1:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/Response.java#L142

which returns a Payload:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/Response.java#L35

we request field 21:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/Response.java#L357

which returns a DeliveryResponse:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/Response.java#L240

we request field 2:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/DeliveryResponse.java#L24

which returns an AndroidAppDeliveryData:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/DeliveryResponse.java#L12

we request field 4, which returns AppFileMetadata:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/AndroidAppDeliveryData.java#L208-L210

we request field 4, which returns a String:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/AppFileMetadata.java#L112

I understand the name is unusual, but it seems my code is faithful to the original Java code. If I made a mistake let me know, but otherwise I am going to keep the code as is. Note that the Java files are dumped from `com.android.vending` 6.1.14 (2016), one of the last versions (if not the last) before Google started obfuscating the field names. So if anyone is aware of a way to get more up to date information, I welcome it.

**Comment by i1v** [comment]
sorry, previous comment used wrong endpoint. For `/fdfe/details`, from Payload we request field 2:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/Response.java#L300

which returns a Details.DetailsResponse:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/Response.java#L221

we request field 4:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/Details.java#L110

which returns a DocV2:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/Details.java#L17

we request field 13:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/DocV2.java#L440

which returns a DocDetails.DocumentDetails:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/DocV2.java#L43

we request field 1:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/DocDetails.java#L38

which returns an AppDetails:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/DocDetails.java#L15

we request field 17, which returns a FileMetadata:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/AppDetails.java#L370-L372

we request field 4, which returns a String:

https://github.com/i1v/googleplay/blob/30cc7928262f19e2d1412b30368962a5f8975017/java/FileMetadata.java#L117

so I do need to update the code.

**Comment by i1v** [comment]
OK this should be fixed now:

https://github.com/i1v/googleplay/blob/e5679e674e323b208c6dba4bcc54a5dfaae1da49/details.go#L193-L196

**Comment by i1v** [comment]
on second thought, I am removing the `Split_ID` method:

https://github.com/i1v/googleplay/blob/3c3a29d42f770cad833d9ae6550ba110a8349760/details.go#L192-L201

I originally merged the two types to save lines of code, not so that people could access field 4 from a details request. However now that people are doing that, I have implemented both types. I can add the method back later if need be, but at least now the code is not misleading.
